### ISSUE TITLE
add arm64 architecture support

### ISSUE THREAD

**Issue by agentS** [tciuro/NanoStore#113]
Although having followed your library build instruction and having run the great library on an old iPhone 4s I am unable to compile the library for usage with a device running a 64 bit ARM processor. Despite of having researched I have not been able to modify the build settings, which are shown in the screenshots below, in order to fit the requirements.

![configuration](https://cloud.githubusercontent.com/assets/5032736/8697950/d9b204b4-2af9-11e5-83de-980a718e206b.png)
![configurationtarget](https://cloud.githubusercontent.com/assets/5032736/8697951/dcceee78-2af9-11e5-88b9-8f1db36fe49b.png)

**Comment by dbottillo** [comment]
same issue here :/

**Comment by tciuro** [comment]
Please let me know if this works for you.

**Comment by dbottillo** [comment]
works for me, thank you very much!!!
